Ignore downloading exercise videos when `projector_key` is None
TRoboto/datacamp-downloader pull request #34
Opened 2021-04-22 20:33 UTC by atlonxp

The downloader is error when the `projector_key` is None, causing failure in the following lines:

```
video = self._get_video(exercise.data.get("projector_key")) # --> video = None
...
if videos and video.video_mp4_link # --> NoneType has no video_mp4_link
```

2021-04-22 21:49 UTC, TRoboto commented
Have you encountered any issue with it? If so please provide with which course.

2021-04-22 21:55 UTC, atlonxp commented
2003 if I can remember. It is a random course ID, and it works fine until I found the error.

Have a look. i have also asked for pull request. 

There is another one when exercise cannot be pulled (aka None)

2021-04-22 21:55 UTC, TRoboto requested changes

2021-04-22 21:55 UTC, TRoboto commented on src/datacamp_downloader/datacamp_utils.py
> +                    if scripts and video.script_link:
For cleaner code, you should revert your changes and add only the following:
`
if not video:
    continue
`

2021-04-23 06:10 UTC, atlonxp commented
changed as your recommended

2021-04-23 21:21 UTC, TRoboto approved these changes

2021-04-23 21:22 UTC, TRoboto commented
Thank you for your contribution.

2021-04-23 21:22 UTC, merged